### PR TITLE
Fix parsing of address field in `pga_hba.conf` (#712)

### LINKED ISSUE #712: Converge fails in `postgresql_access`-resource
## :ghost: Brief Description

~Under some currently unidentified circumstances~ When the host portion inside the `pg_hba.conf` file isn't an IP address, the converge fails during processing of the `postgresql_access`-resource.

## :pancakes: Cookbook version

11.0.1

## :woman_cook:  Chef-Infra Version

17.10.0

## :tophat: Platform details

Debian 11

## Steps To Reproduce

1. Consider the following recipe

```ruby
postgresql_install 'install' do
  version 13

  action [ :install, :init_server ]
end

postgresql_config 'config'

postgresql_access 'postgres' do
  type 'local'
  user 'postgres'
  database 'all'
  auth_method 'peer'
end

postgresql_service 'postgresql' do
  action [ :start, :enable ]
end

postgresql_access 'foo allow local' do
  type 'local'
  user 'foo'
  database 'postgres'
  auth_method 'peer'
end

postgresql_access 'foo reject remote' do
  type 'host'
  user 'foo'
  database 'all'
  address 'all'
  auth_method 'reject'
end
```

2. Converge one time (it succeeds)
3. Converge a second time (it fails)

```
       Cinc Client, version 17.10.0
       Patents: https://www.chef.io/patents
       Infra Phase starting
       Resolving cookbooks for run list: ["apt::default", "test::test"]
       Synchronizing cookbooks:
         - apt (7.4.3)
         - yum (7.4.1)
         - postgresql (11.0.1)
         - test (1.0.0)
       Installing cookbook gem dependencies:
       Compiling cookbooks...
       Loading Cinc Auditor profile files:
       Loading Cinc Auditor input files:
       Loading Cinc Auditor waiver files:
       Converging 16 resources
       Recipe: apt::default
         * file[/var/lib/apt/periodic/update-success-stamp] action nothing (skipped due to action :nothing)
         * apt_update[periodic] action periodic (up to date)
         * execute[apt-get update] action nothing (skipped due to action :nothing)
         * execute[apt-get autoremove] action nothing (skipped due to action :nothing)
         * execute[apt-get autoclean] action nothing (skipped due to action :nothing)
         * directory[/var/cache/local] action create (up to date)
         * directory[/var/cache/local/preseeding] action create (up to date)
         * template[/etc/apt/apt.conf.d/10dpkg-options] action create (up to date)
         * template[/etc/apt/apt.conf.d/10recommends] action create (up to date)
         * apt_package[apt-transport-https, gnupg, dirmngr] action install (up to date)
       Recipe: test::test
         * postgresql_install[install] action install
           * apt_update[] action periodic (up to date)
           * apt_package[apt-transport-https] action install (up to date)
           * apt_repository[postgresql_org_repository_13] action add
             * execute[apt-cache gencaches] action nothing (skipped due to action :nothing)
             * apt_update[postgresql_org_repository_13] action nothing (skipped due to action :nothing)
             * remote_file[/tmp/kitchen/cache/https___download_postgresql_org_pub_repos_apt_ACCC4CF8_asc] action create (up to date)
             * execute[apt-key add /tmp/kitchen/cache/https___download_postgresql_org_pub_repos_apt_ACCC4CF8_asc] action run (skipped due to not_if)
             * file[/etc/apt/sources.list.d/postgresql_org_repository_13.list] action create (up to date)
       (up to date)
            (up to date)
         * apt_update[] action periodic (up to date)
         * apt_package[apt-transport-https] action install (up to date)
         * apt_repository[postgresql_org_repository_13] action add
           * execute[apt-cache gencaches] action nothing (skipped due to action :nothing)
           * apt_update[postgresql_org_repository_13] action nothing (skipped due to action :nothing)
           * remote_file[/tmp/kitchen/cache/https___download_postgresql_org_pub_repos_apt_ACCC4CF8_asc] action create (up to date)
           * execute[apt-key add /tmp/kitchen/cache/https___download_postgresql_org_pub_repos_apt_ACCC4CF8_asc] action run (skipped due to not_if)
           * file[/etc/apt/sources.list.d/postgresql_org_repository_13.list] action create (up to date)
            (up to date)
          (up to date)
       * apt_package[postgresql-client] action install (up to date)
       * ohai[postgresql_client_packages] action nothing (skipped due to action :nothing)
        (up to date)
       * apt_package[postgresql-server] action install (up to date)
       * ohai[postgresql_server_packages] action nothing (skipped due to action :nothing)
       * template[/etc/postgresql-common/createcluster.conf] action create (up to date)
        (up to date)
        (up to date)
       * postgresql_install[install] action init_server (up to date)
       * postgresql_config[config] action create (up to date)
       * postgresql_access[postgres] action create
         
         ================================================================================
         Error executing action `create` on resource 'postgresql_access[postgres]'
         ================================================================================
         
         ArgumentError
         -------------
         missing keyword: :address
         
         Cookbook Trace: (most recent call first)
         ----------------------------------------
         /tmp/kitchen/cache/cookbooks/postgresql/libraries/access.rb:268:in `initialize'
         /tmp/kitchen/cache/cookbooks/postgresql/libraries/access.rb:230:in `new'
         /tmp/kitchen/cache/cookbooks/postgresql/libraries/access.rb:230:in `create'
         /tmp/kitchen/cache/cookbooks/postgresql/libraries/access.rb:161:in `block in marshall_entries'
         /tmp/kitchen/cache/cookbooks/postgresql/libraries/access.rb:161:in `each'
         /tmp/kitchen/cache/cookbooks/postgresql/libraries/access.rb:161:in `marshall_entries'
         /tmp/kitchen/cache/cookbooks/postgresql/libraries/access.rb:93:in `read!'
         /tmp/kitchen/cache/cookbooks/postgresql/libraries/access.rb:139:in `read'
         /tmp/kitchen/cache/cookbooks/postgresql/resources/access.rb:64:in `block in class_from_file'
         
         Resource Declaration:
         ---------------------
         # In /tmp/kitchen/cache/cookbooks/test/recipes/test.rb
         
           9: postgresql_access 'postgres' do
          10:   type 'local'
          11:   user 'postgres'
          12:   database 'all'
          13:   auth_method 'peer'
          14: end
          15: 
         
         Compiled Resource:
         ------------------
         # Declared in /tmp/kitchen/cache/cookbooks/test/recipes/test.rb:9:in `from_file'
         
         postgresql_access("postgres") do
           action [:create]
           default_guard_interpreter :default
           declared_type :postgresql_access
           cookbook_name "test"
           recipe_name "test"
           type "local"
           user "postgres"
           database "all"
           auth_method "peer"
           config_file "/etc/postgresql/13/main/pg_hba.conf"
           owner "postgres"
           group "root"
           filemode "0600"
         end
         
         System Info:
         ------------
         chef_version=17.10.0
         platform=debian
         platform_version=11
         ruby=ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
         program_name=/opt/cinc/bin/cinc-client
         executable=/opt/cinc/bin/cinc-client
         
       
       Running handlers:
       [2022-12-16T19:23:43+01:00] ERROR: Running exception handlers
       Running handlers complete
       [2022-12-16T19:23:43+01:00] ERROR: Exception handlers complete
       Infra Phase failed. 0 resources updated in 04 seconds
       [2022-12-16T19:23:43+01:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/cinc-stacktrace.out
       [2022-12-16T19:23:43+01:00] FATAL: ---------------------------------------------------------------------------------------
       [2022-12-16T19:23:43+01:00] FATAL: PLEASE PROVIDE THE CONTENTS OF THE stacktrace.out FILE (above) IF YOU FILE A BUG REPORT
       [2022-12-16T19:23:43+01:00] FATAL: ---------------------------------------------------------------------------------------
       [2022-12-16T19:23:43+01:00] FATAL: ArgumentError: postgresql_access[postgres] (test::test line 9) had an error: ArgumentError: missing keyword: :address
```

## :police_car: Expected behavior

Each converge run after the initial run should succeed.

## :heavy_plus_sign: Additional context

Despite the error occurs inside the first `postgresql_access`-ressource, it is triggered by the both `postgresql_access`-ressource for the user `foo`. The content of the `pg_hba.conf`-file is:

```
#
# Generated by Chef for test-debian-11.vagrantup.com
# Do NOT modify this file by hand.
#

# TYPE  DATABASE        USER            ADDRESS                 METHOD         OPTIONS
local   all             postgres                                peer
local   all             all                                     peer
host    all             all             127.0.0.1/32            md5
host    all             all             ::1/128                 md5
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            md5
host    replication     all             ::1/128                 md5
local   postgres        foo                                     peer
host    all             foo             all                     reject
```

### PR DESCRIPTION
**Pull request by hamarituc**
#  Description

Now also hostnames and `all` are allowed for the `address`-property of the `postgresql_access`-resource.

## Issues Resolved

* closes #712

## Check List

- [x] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [x] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

File: libraries/access.rb [hunk 1]
```diff
@@ -70,7 +70,7 @@ class PgHbaFile
 
           attr_reader :entries
 
-          SPLIT_REGEX = %r{^(?<type>\w+)\s+(?<database>\w+)\s+(?<user>\w+)\s+(?<address>[\d.:\/]+)?(?:\s*)(?<auth_method>[\w-]+)(?:\s*)(?<auth_options>[\w=-]+)?(?:\s*)(?<comment>#\s*.*)?$}.freeze
+          SPLIT_REGEX = %r{^(((?<type>local)\s+(?<database>\w+)\s+(?<user>\w+))|((?!local)(?<type>\w+)\s+(?<database>\w+)\s+(?<user>\w+)\s+(?<address>[\w\-.:\/]+)))\s+(?<auth_method>[\w-]+)(?:\s*)(?<auth_options>[\w=-]+)?(?:\s*)(?<comment>#\s*.*)?$}.freeze
```
Comment (bmhughes) [inline libraries/access.rb:73]: If we're just looking to match a hostname or fqdn in the address field is there any reason we can't just add `\w` to the address capture group character class?

ie:
```ruby
^(?<type>\w+)\s+(?<database>\w+)\s+(?<user>\w+)\s+(?<address>[\w\d.:\/]+)?(?:\s*)(?<auth_method>[\w-]+)(?:\s*)(?<auth_options>[\w=-]+)?(?:\s*)(?<comment>#\s*.*)?$
```

I'm not a big fan of making the regex any more complicated than it absolutely needs to be and as long as it (reasonably, it is a regex afterall) reliably breaks up the entry I'm happy with it. If we needed any validation fields etc. they'd be best implemented in the class representing an entry instead.

Comment (hamarituc) [reply libraries/access.rb:73]: This my first thought, too. But this makes the expression ambiguous, as it doesn't skip the `address` field for `local`-rules. See:

```
irb(main):002:0> %r'^(?<type>\w+)\s+(?<database>\w+)\s+(?<user>\w+)\s+(?<address>[\w\d.:\/]+)?(?:\s*)(?<auth_method>[\w-]+)(?:\s*)(?<auth_op
tions>[\w=-]+)?(?:\s*)(?<comment>#\s*.*)?$'.match('local   foo     postgres    peeer').named_captures.compact.transform_keys(&:to_sym)
=> {:type=>"local", :database=>"foo", :user=>"postgres", :address=>"peee", :auth_method=>"r"}
```

Comment (bmhughes) [reply libraries/access.rb:73]: Missed that, apologies. Bloody regex strikes again. I'm still not **loving** it but might be the best we can do, I tried my best to avoid using a regex in the first place but dealing with comments made it a requirement.

**Review by bmhughes — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [11.1.1](https://github.com/sous-chefs/postgresql/releases/tag/11.1.1)
